export const STATIC_ICON_LIST = Object.freeze({
  angleDown: 'angle-down',
  angleDownBlue: 'angle-down-blue',
  angleRight: 'angle-right',
  angleUpBlue: 'angle-up-blue',
  arrowDown: 'arrow-down',
  arrowUpRight: 'arrow-up-right',
  bell: 'bell',
  bellFill: 'bell-fill',
  calendarNext: 'calendar-next',
  calendarPrev: 'calendar-prev',
  check: 'check',
  checkThick: 'check-thick',
  chevronRight: 'chevron-right',
  commentCircle: 'comment-circle',
  file: 'file',
  hashtag: 'hashtag',
  home: 'home',
  homeFill: 'home-fill',
  logo: 'logo',
  mypage: 'mypage',
  mypageFill: 'mypage-fill',
  nestedArrow: 'nested-arrow',
  noticeBell: 'notice-bell',
  noticeBellBlue: 'notice-bell-blue',
  pointCircle: 'point-circle',
  pencil: 'pencil',
  pencilBlue: 'pencil-blue',
  search: 'search',
  searchThick: 'search-thick',
  share: 'share',
  test: 'test',
  testFill: 'test-fill',
  trash: 'trash',
  video: 'video',
  videoFill: 'video-fill',
  movie: 'movie',
  location: 'location',
  person: 'person',
  host: 'host',
});

export const FILL_ICON_LIST = Object.freeze({
  arrowLeft: 'arrow-left',
  bookmarkFill: 'bookmark-fill',
  closedEye: 'closed-eye',
  like: 'like',
  openedEye: 'opened-eye',
});

export const STROKE_ICON_LIST = Object.freeze({
  pencilUnderline: 'pencil-underline',
  x: 'x',
});

export const ILLUSTRATION_ICON_LIST = Object.freeze({
  starNoComment: 'star-no-comment',
  starNoPost: 'star-no-post',
  starNoReview: 'star-no-review',
});
