export const STATIC_ICON_LIST = Object.freeze({
  abuseComment: 'abuse-comment',
  adult: 'adult',
  angleDown: 'angle-down',
  angleDownBlue: 'angle-down-blue',
  angleRight: 'angle-right',
  angleUpBlue: 'angle-up-blue',
  arrowDown: 'arrow-down',
  arrowUpRight: 'arrow-up-right',
  ban: 'ban',
  bell: 'bell',
  bellFill: 'bell-fill',
  blackCloud: 'black-cloud',
  blueCamera: 'blue-camera',
  blueTriangle: 'blue-triangle',
  calendar: 'calendar',
  calendarNext: 'calendar-next',
  calendarPrev: 'calendar-prev',
  camera: 'camera',
  check: 'check',
  checkCircle: 'check-circle',
  checkCircleFill: 'check-circle-fill',
  checkThick: 'check-thick',
  chevronRight: 'chevron-right',
  comment: 'comment',
  commentCircle: 'comment-circle',
  file: 'file',
  flag: 'flag',
  flagBlue: 'flag-blue',
  flagPink: 'flag-pink',
  hashtag: 'hashtag',
  hashtagFill: 'hashtag-fill',
  listBullet: 'list-bullet',
  listOrdered: 'list-ordered',
  heartMinus: 'heart-minus',
  heartPlus: 'heart-plus',
  home: 'home',
  homeFill: 'home-fill',
  logo: 'logo',
  mypage: 'mypage',
  mypageFill: 'mypage-fill',
  noticeBellBlue: 'notice-bell-blue',
  pointCircleBlue: 'point-circle-blue',
  starCircle: 'star-circle',
  test: 'test',
  testFill: 'test-fill',
  triangleExclamationCircle: 'triangle-exclamation-circle',
  trash: 'trash',
  user: 'user',
  video: 'video',
  videoFill: 'video-fill',
  movie: 'movie',
  location: 'location',
  person: 'person',
  host: 'host',
});

export const FILL_ICON_LIST = Object.freeze({
  arrowLeft: 'arrow-left',
  bookmarkFill: 'bookmark-fill',
  closedEye: 'closed-eye',
  like: 'like',
  openedEye: 'opened-eye',
});

export const STROKE_ICON_LIST = Object.freeze({
  pencilUnderline: 'pencil-underline',
  x: 'x',
});

export const ILLUSTRATION_ICON_LIST = Object.freeze({
  starNoComment: 'star-no-comment',
  starNoPost: 'star-no-post',
  starNoReview: 'star-no-review',
});
